#! /bin/sh

RUNIT_DIR=/usr/sbin

#env  | sed -e 's/=/="/' | sed -e 's/$/"/' > /etc/envvars
for K in $(env | cut -d= -f1)
do
    VAL=$(eval echo \$$K)
    echo "${K}=\"${VAL}\"" >> /etc/envvars
done

sv_stop() {
    echo "*** Stopping services"
    for s in $(ls -d /etc/service/*)
    do
        $RUNIT_DIR/sv stop $s
    done
}

echo "Starting pre-service scripts in /etc/runit_init.d"
for script in /etc/runit_init.d/*
do
    if [ -x "$script" ]; then
        echo >&2 "*** Running: $script"
        $script
        retval=$?
        if [ $retval != 0 ];
        then
            echo >&2 "*** Failed with return value: $?"
            exit $retval
        fi
    fi
done

trap "sv_stop; exit" SIGTERM


if [ $# -eq 0 ]; then
	echo "Press Ctrl-C to shut down"
	$RUNIT_DIR/runsvdir -P /etc/service &
	wait
else
	$RUNIT_DIR/runsvdir -P /etc/service &
	[ "$1" == '--' ] && shift
	echo "Running $@"
	exec $@
fi
