#!/bin/bash -e

chown www-data /srv/www

if [ ! -z /scripts/init.sh ] && [ -x /scripts/init.sh ]; then
	sudo -E -u www-data /scripts/init.sh >> /dev/null
fi

/scripts/nginx-config.sh /etc/nginx/sites-enabled/default 2>&1

service nginx reload >> /dev/null

exec sleep infinity
