#!/bin/bash -e

chown -R nginx:nginx /srv/www

if [ -n "$SET_REAL_IP_FROM" ]; then
  echo "set_real_ip_from $SET_REAL_IP_FROM;" > /etc/nginx/conf.d/set_real_ip_from.conf
else
  rm -f /etc/nginx/conf.d/set_real_ip_from.conf
fi

OUTFILE=/etc/nginx/conf.d/default.conf

if [ -z "${GITHUB_WEBHOOK}" ]; then
GITHUB_WEBHOOK=webhook
fi

if [ -z "${ROOT_PATH}" ]; then
ROOT_PATH=/srv/www/
fi

echo """server {
    listen 80 default_server backlog=2048;
    root ${ROOT_PATH};
    index index.html;
    error_page 404 404.html;
    """ > $OUTFILE

echo """
        location /$GITHUB_WEBHOOK {
		rewrite  ^ / break;
		proxy_pass http://127.0.0.1:9001;
	}""" >> $OUTFILE

echo """
        location / {
        try_files \$uri \$uri/ =404;
	}
}""" >> $OUTFILE

exec /usr/sbin/nginx -g 'daemon off;' 2>&1
